"""empty message

Revision ID: 5fa2ec9a85ca
Revises: 
Create Date: 2020-12-15 11:47:15.694962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fa2ec9a85ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('profile', sa.Text(), nullable=True),
    sa.Column('encrypted_password', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('coffees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('bean_id', sa.Integer(), nullable=False),
    sa.Column('dripper_id', sa.Integer(), nullable=False),
    sa.Column('extraction_time', sa.Integer(), nullable=True),
    sa.Column('extraction_method_id', sa.Integer(), nullable=True),
    sa.Column('mesh_id', sa.Integer(), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('powder_amount', sa.Integer(), nullable=False),
    sa.Column('water_amount', sa.Integer(), nullable=True),
    sa.Column('water_temperature', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dripper_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drinkers',
    sa.Column('coffee_id', sa.Integer(), nullable=True),
    sa.Column('drinker_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['coffee_id'], ['coffees.id'], ),
    sa.ForeignKeyConstraint(['drinker_id'], ['users.id'], )
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bitterness', sa.Integer(), nullable=False),
    sa.Column('want_repeat', sa.Integer(), nullable=False),
    sa.Column('situation', sa.Integer(), nullable=False),
    sa.Column('strongness', sa.Integer(), nullable=False),
    sa.Column('feeling', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('coffee_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['coffee_id'], ['coffees.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('drinkers')
    op.drop_table('coffees')
    op.drop_table('users')
    # ### end Alembic commands ###
