"""coffee has some drinker

Revision ID: d472c83898fc
Revises: 
Create Date: 2020-12-03 16:06:34.256654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd472c83898fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drinkers',
    sa.Column('coffee_id', sa.Integer(), nullable=True),
    sa.Column('drinker_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['coffee_id'], ['coffees.id'], ),
    sa.ForeignKeyConstraint(['drinker_id'], ['users.id'], )
    )
    op.drop_constraint('coffees_drinker_id_fkey', 'coffees', type_='foreignkey')
    op.drop_column('coffees', 'drinker_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coffees', sa.Column('drinker_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('coffees_drinker_id_fkey', 'coffees', 'users', ['drinker_id'], ['id'])
    op.drop_table('drinkers')
    # ### end Alembic commands ###
