"""empty message

Revision ID: dfdd2d02889f
Revises: d472c83898fc
Create Date: 2020-12-08 16:05:11.577621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfdd2d02889f'
down_revision = 'd472c83898fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coffees', sa.Column('memo', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coffees', 'memo')
    # ### end Alembic commands ###
